---
title: "Latex test"
author: "Mark Hand"
date: "6/15/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval=FALSE, cache = TRUE, message=FALSE, warning=FALSE)
library(haven) # import .dta
suppressMessages(library("tidyverse")) # everything 
library(plm) # For linear panel regression
library(stargazer) # For regression outputs #fail 
library(texreg) # For regression outputs #fail 
library(kableExtra) # For regression outputs 
library(broom) # Because Matt Worthington said so 
library(knitr) # Because Matt Worthington said so 

```

```{r data import, eval=T, message=F, warning=F}
# Alt and Lassen's "Enforcement and Public Corruption: Evidence from US States"
# http://epstein.wustl.edu/research/LPE.Alt.pdf
AltLassen <- read_dta("data/Replication/AltLassenJLEO.dta")

# Michael Barber's "Ideological Donors, Contribution Limits, and the Polarization of American Legislatures"  
# https://doi.org/10.1086/683453
Barber <- read_csv("~/Documents/GitHub/Money-in-Politics/data/Barber/Barber_Limits_Data.csv")

# Data from ICC 
# www.greasethewheels.org/cci/
convictions <- read_csv("~/Documents/GitHub/Money-in-Politics/data/ICS/CCI19762015.csv")
reflections <- read_csv("~/Documents/GitHub/Money-in-Politics/data/ICS/CRI19772013.csv")
```

```{r panel data wrangling, eval=T}
# Combining Barber and ICS 
corruption <- full_join(convictions, reflections)
corruption <- corruption %>% 
  rename("st"="State", "year"="Year")
corruption$st <- state.abb[match(corruption$st,state.name)]
BarberICC <- left_join(Barber, corruption)

BarberICC <- BarberICC %>% 
  mutate(
    ind_limits_dummy = ifelse(ind_limits_2010==99999,0,1),
    ind2pty_limits_dummy = ifelse(ind2pty_limits_2010==99999,0,1),
    pac_limits_dummy = ifelse(pac_limits_2010==99999,0,1),
    total_limits_dummy = ifelse(total_limits_2010==99999,0,1)
  )

# Adding AltLassen
# table(AltLassen$state_name)
AltLassen$state_name[AltLassen$state_name=="Californ"] = "California"
AltLassen$state_name[AltLassen$state_name=="Connecti"] = "Connecticut"
AltLassen$state_name[AltLassen$state_name=="Louisian"] = "Louisiana"
AltLassen$state_name[AltLassen$state_name=="Massachu"] = "Massachusetts"
AltLassen$state_name[AltLassen$state_name=="Minnesot"] = "Minnesota"
AltLassen$state_name[AltLassen$state_name=="Mississi"] = "Mississippi"
AltLassen$state_name[AltLassen$state_name=="NewHamps"] = "New Hampshire"
AltLassen$state_name[AltLassen$state_name=="NewJerse"] = "New Jersey"
AltLassen$state_name[AltLassen$state_name=="NewMexic"] = "New Mexico"
AltLassen$state_name[AltLassen$state_name=="NewYork"] = "New York"
AltLassen$state_name[AltLassen$state_name=="NorthCar"] = "North Carolina"
AltLassen$state_name[AltLassen$state_name=="NorthDak"] = "North Dakota"
AltLassen$state_name[AltLassen$state_name=="Pennsylv"] = "Pennsylvania"
AltLassen$state_name[AltLassen$state_name=="RhodeIsl"] = "Rhode Island"
AltLassen$state_name[AltLassen$state_name=="SouthCar"] = "South Carolina"
AltLassen$state_name[AltLassen$state_name=="SouthDak"] = "South Dakota"
AltLassen$state_name[AltLassen$state_name=="Tennesse"] = "Tennessee"
AltLassen$state_name[AltLassen$state_name=="Washingt"] = "Washington"
AltLassen$state_name[AltLassen$state_name=="WestVirg"] = "West Virginia"
AltLassen$state_name[AltLassen$state_name=="Wisconsi"] = "Wisconsin"
AltLassen$state_name <- state.abb[match(AltLassen$state_name,state.name)]
AltLassen <- AltLassen %>% 
  rename("st"="state_name")
AltLassen$year <-as.integer(AltLassen$year)

AltBarber <- inner_join(BarberICC, AltLassen)
```

```{r panel modeling, eval=T}
## CCI 
# Individual limits and corruption
CCIreg1  <- plm(CCI ~ ind_limits_2010*ind_limits_dummy,data = BarberICC, index = c("st","year"), effect="twoways")
# No signifigance

# Individual-to-party limits and corruption
CCIreg2  <- plm(CCI ~ ind2pty_limits_2010*ind2pty_limits_dummy,data = BarberICC, index = c("st","year"), effect="twoways")
# No Signifigance

# PAC Limits and corruption
CCIreg3  <- plm(CCI ~ pac_limits_2010*pac_limits_dummy,data = BarberICC, index = c("st","year"), effect="twoways")
# No Signifigance

# Total Limits and corruption
CCIreg4  <- plm(CCI ~ total_limits_2010*total_limits_dummy,data = BarberICC, index = c("st","year"), effect="twoways")
# One star. Hmm...

# Everybody? 
CCIreg5 <- plm(CCI ~ ind_limits_2010*ind_limits_dummy + ind2pty_limits_2010*ind2pty_limits_dummy + pac_limits_2010*pac_limits_dummy, data = BarberICC, index = c("st","year"), effect="twoways")

## CRI
CRIreg1  <- plm(CRI ~ ind_limits_2010*ind_limits_dummy,data = BarberICC, index = c("st","year"), effect="twoways")
# No signifigance 

# Individual-to-party limits and reflection
CRIreg2  <- plm(CRI ~ ind2pty_limits_2010*ind2pty_limits_dummy,data = BarberICC, index = c("st","year"), effect="twoways")
# One star. Hmm... 

# PAC Limits and reflection
CRIreg3  <- plm(CRI ~ pac_limits_2010*pac_limits_dummy,data = BarberICC, index = c("st","year"), effect="twoways")
# No Signifigance

# All Limits and reflection
CRIreg4  <- plm(CRI ~ total_limits_2010*total_limits_dummy,data = BarberICC, index = c("st","year"), effect="twoways")
# No Signifigance 

# Everybody? 
CRIreg5 <- plm(CRI ~ ind_limits_2010*ind_limits_dummy + ind2pty_limits_2010*ind2pty_limits_dummy + pac_limits_2010*pac_limits_dummy, data = BarberICC, index = c("st","year"), effect="twoways")
```

```{r (old) controlled panel modeling}
#Next: Panel model of corruption against unemployment and high school? 
testmodel01 <- plm(CCI ~ rpcinc_annual_new + unemp + high_school + logNumpop + citi6006 + grelimp, data = AltBarber, index = c("st","year"), effect="twoways")

testmodel02 <- plm(CCI ~ jdiv + bindingonetermlimit + bindingtwotermlimit + rpcinc_annual_new + eousa + unemp + citi6006 + high_school + rgenrevpc + logNumpop + eopop + men_ineqincwag + grelimp + fedrepcons + urbanization_2 + logpop + inspop, data = AltBarber, index = c("st","year"), effect="twoways")

testmodel03 <- plm(CCI ~ jdiv + bindingonetermlimit + bindingtwotermlimit + rpcinc_annual_new + eousa + unemp + citi6006 + high_school + rgenrevpc + logNumpop + eopop + men_ineqincwag + grelimp + fedrepcons + urbanization_2 + logpop + inspop + ind_limits_2010*ind_limits_dummy + ind2pty_limits_2010*ind2pty_limits_dummy + pac_limits_2010*pac_limits_dummy, data = AltBarber, index = c("st","year"), effect="twoways")

testmodel05 <- plm(CCI ~ jdiv + bindingonetermlimit + bindingtwotermlimit + rpcinc_annual_new + eousa + unemp + citi6006 + high_school + rgenrevpc + logNumpop + eopop + men_ineqincwag + grelimp + urbanization_2 + logpop + inspop, data = AltBarber, index = c("st","year"), effect="twoways")
```

```{r controlled panel modeling, eval=T}

CCIcontrol01 <- plm(CCI ~ jdiv  # Divided government 
                   + bindingonetermlimit # Binding one-term limit 
                   + bindingtwotermlimit # Binding two-term limit 
                   + rpcinc_annual_new # Real per capita income ($1000)
                   + eopop # AUSAs per million population
                   + unemp # Unemployment 
                   + citi6006 # Citizen ideology measure 
                   + high_school + # Percent high school graduates
                   + rgenrevpc # Real per capita gov revenues ($1000)
                   + men_ineqincwag # Inequality: Male wages
                   + grelimp # Relative government wages
                   + urbanization_2 # Urbanization 
                   + logpop, # Log of population (millions)
                   data = AltBarber, 
                   index = c("st","year"), 
                   effect="twoways")

CCIcontrol02 <- plm(CCI ~ jdiv  # Divided government 
                   + bindingonetermlimit # Binding one-term limit 
                   + bindingtwotermlimit # Binding two-term limit 
                   + rpcinc_annual_new # Real per capita income ($1000)
                   + eopop # AUSAs per million population
                   + unemp # Unemployment 
                   + citi6006 # Citizen ideology measure 
                   + high_school + # Percent high school graduates
                   + rgenrevpc # Real per capita gov revenues ($1000)
                   + men_ineqincwag # Inequality: Male wages
                   + grelimp # Relative government wages
                   + urbanization_2 # Urbanization 
                   + logpop # Log of population (millions)
                   + ind_limits_2010*ind_limits_dummy 
                   + ind2pty_limits_2010*ind2pty_limits_dummy 
                   + pac_limits_2010*pac_limits_dummy, 
                   data = AltBarber, 
                   index = c("st","year"), 
                   effect="twoways")

CRIcontrol01 <- plm(CRI ~ jdiv  # Divided government 
                   + bindingonetermlimit # Binding one-term limit 
                   + bindingtwotermlimit # Binding two-term limit 
                   + rpcinc_annual_new # Real per capita income ($1000)
                   + eopop # AUSAs per million population
                   + unemp # Unemployment 
                   + citi6006 # Citizen ideology measure 
                   + high_school + # Percent high school graduates
                   + rgenrevpc # Real per capita gov revenues ($1000)
                   + men_ineqincwag # Inequality: Male wages
                   + grelimp # Relative government wages
                   + urbanization_2 # Urbanization 
                   + logpop, # Log of population (millions)
                   data = AltBarber, 
                   index = c("st","year"), 
                   effect="twoways")

CRIcontrol02 <- plm(CRI ~ jdiv  # Divided government 
                   + bindingonetermlimit # Binding one-term limit 
                   + bindingtwotermlimit # Binding two-term limit 
                   + rpcinc_annual_new # Real per capita income ($1000)
                   + eopop # AUSAs per million population
                   + unemp # Unemployment 
                   + citi6006 # Citizen ideology measure 
                   + high_school + # Percent high school graduates
                   + rgenrevpc # Real per capita gov revenues ($1000)
                   + men_ineqincwag # Inequality: Male wages
                   + grelimp # Relative government wages
                   + urbanization_2 # Urbanization 
                   + logpop # Log of population (millions)
                   + ind_limits_2010*ind_limits_dummy 
                   + ind2pty_limits_2010*ind2pty_limits_dummy 
                   + pac_limits_2010*pac_limits_dummy, 
                   data = AltBarber, 
                   index = c("st","year"), 
                   effect="twoways")
                 
```

```{r DiD wrangling, eval=T}
BarberICC %>% arrange(year) %>% group_by(st) %>% mutate(
  ind_d = (ind_limits_2010 - dplyr::lag(ind_limits_2010)),
  ind_dummy_d = (ind_limits_dummy - dplyr::lag(ind_limits_dummy)),
  pac_d = (pac_limits_2010 - dplyr::lag(pac_limits_2010)),
  pac_dummy_d = (pac_limits_dummy - dplyr::lag(pac_limits_dummy)),
  ind2pty_d = (ind2pty_limits_2010 - dplyr::lag(ind2pty_limits_2010)),
  ind2pty_dummy_d = (ind2pty_limits_dummy - dplyr::lag(ind2pty_limits_dummy))
  ) -> testframe

testframe %>% dplyr::select(1:2,8,11,3:7,12:21) -> DiDsmall 

# Now I have what I think are three multi-level categorical independent variables. 
# https://stats.idre.ucla.edu/r/modules/coding-for-categorical-variables-in-regression-models/
#1. When limits were imposed (1) or went down, did corruption go down? 
#2. When limits were removed (-1) or went up, did corruption go up? 

DiDsmall$ind_dummy_f <- factor(DiDsmall$ind_dummy_d)
DiDsmall <- within(DiDsmall, ind_dummy_f <- relevel(ind_dummy_f, ref = "0"))
DiDsmall$pac_dummy_f <- factor(DiDsmall$pac_dummy_d)
DiDsmall <- within(DiDsmall, pac_dummy_f <- relevel(pac_dummy_f, ref = "0"))
DiDsmall$ind2pty_dummy_f <- factor(DiDsmall$ind2pty_dummy_d)
DiDsmall <- within(DiDsmall, ind2pty_dummy_f <- relevel(ind2pty_dummy_f, ref = "0"))
```

```{r DiD modeling, eval=T}
#summary(lm(CCI ~ ind_dummy_f, data = DiDsmall))
#summary(lm(CCI ~ pac_dummy_f, data = DiDsmall))
#summary(lm(CCI ~ ind2pty_dummy_f, data = DiDsmall))
#summary(lm(CRI ~ ind_dummy_f, data = DiDsmall))
#summary(lm(CRI ~ pac_dummy_f, data = DiDsmall))
#summary(lm(CRI ~ ind2pty_dummy_f, data = DiDsmall))
# No effects 

CCIDID01 <- lm(CCI ~ ind_dummy_f*ind_d, data = DiDsmall)
CCIDID02 <- lm(CCI ~ pac_dummy_f*pac_d, data = DiDsmall)
CCIDID03 <- lm(CCI ~ ind2pty_dummy_f*ind2pty_d, data = DiDsmall)

CRIDID01 <- lm(CRI ~ ind_dummy_f*ind_d, data = DiDsmall)
CRIDID02 <- lm(CRI ~ pac_dummy_f*pac_d, data = DiDsmall)
CRIDID03 <- lm(CRI ~ ind2pty_dummy_f*ind2pty_d, data = DiDsmall)
# No effects 
# Next: Lag?  
```

```{r stargzer CCI html}
stargazer(CCIreg1, CCIreg2, CCIreg3, CCIreg5,
  type="text", 
  title = "Are campaign limits and corruption convictions correlated?",
  out="collateral/CCI.htm",
  dep.var.labels = c("Corruption Convictions Index"),
  covariate.labels=c("Individual limit amounts", "Individual limits (dummy)","Individual-to-party limit amount","Individual-to-party limits (dummy)","PAC limit amounts","PAC limits (dummy)"))
```

```{r stargazer CCI latex, results="asis", eval=T}
stargazer(CCIreg1, CCIreg2, CCIreg3, CCIreg5,
  type="latex", 
  title = "Are campaign limits and corruption convictions correlated?",
  dep.var.labels = c("Corruption Convictions Index"),
  covariate.labels=c("Individual limit amounts", "Individual limits (dummy)","Individual-to-party limit amount","Individual-to-party limits (dummy)","PAC limit amounts","PAC limits (dummy)"))
```

```{r stargazer CRI html}
stargazer(CRIreg1, CRIreg2, CRIreg3, CRIreg5,
  type="text", 
  title = "Are campaign limits and corruption reflections correlated?",
  out="collateral/CRI.htm",
  dep.var.labels = c("Corruption Reflections Index"),
  covariate.labels=c("Individual limit amounts", "Individual limits (dummy)","Individual-to-party limit amount","Individual-to-party limits (dummy)","PAC limit amounts","PAC limits (dummy)"))
```

```{r stargazer CRI latex, results="asis", eval=T}
stargazer(CRIreg1, CRIreg2, CRIreg3, CRIreg5,
  title = "Are campaign limits and corruption reflections correlated?",
  dep.var.labels = c("Corruption Reflections Index"),
  covariate.labels=c("Individual limit amounts", "Individual limits (dummy)","Individual-to-party limit amount","Individual-to-party limits (dummy)","PAC limit amounts","PAC limits (dummy)"))
```

```{r stargazer controlled panel}
stargazer(CCIcontrol01,CCIcontrol02,CRIcontrol01,CRIcontrol02,
  type="text", 
  out="collateral/CCICRIcontrol.htm",
  dep.var.labels = c("Corruption Convictions Index", "Corruption Reflections Index"),
  covariate.labels=c("Divided government", "Binding one-term limit"," Binding two-term limit","Real per capita income ($1000)","AUSAs per million population","Unemployment","Citizen ideology measure","Percent high school graduates","Real per capita gov revenues ($1000)","Inequality: Male wages","Relative government wages","Urbanization","Log of population (millions)","Individual limit amounts", "Individual limits (dummy)","Individual-to-party limit amount","Individual-to-party limits (dummy)","PAC limit amounts","PAC limits (dummy)")
  )
```

```{r stargazer controlled panel latex, results="asis", eval=T}
stargazer(CCIcontrol01,CCIcontrol02,CRIcontrol01,CRIcontrol02,
  dep.var.labels = c("Corruption Convictions Index", "Corruption Reflections Index"),
  covariate.labels=c("Divided government", "Binding one-term limit"," Binding two-term limit","Real per capita income (thousands)","AUSAs per million population","Unemployment","Citizen ideology measure","Percent high school graduates","Real per capita gov revenues (thousands)","Inequality: Male wages","Relative government wages","Urbanization","Log of population (millions)","Individual limit amounts", "Individual limits (dummy)","Individual-to-party limit amount","Individual-to-party limits (dummy)","PAC limit amounts","PAC limits (dummy)")
  )
```

```{r stargazer DiD}
stargazer(CCIDID01, CCIDID02, CCIDID03, CRIDID01, CRIDID02, CRIDID03,
  type="text", 
  title = "Do changes in limits lead to lower levels of corruption?",
  out="collateral/DiD.htm",
  dep.var.labels = c("Corruption Convictions Index", "Corruption Reflections Index"),
  covariate.labels=c("Individual limits removed","Individual limits imposed","Individual limit amount","Individual limits removed*amount","Individual limits imposed*amount",
                     "PAC limits removed","PAC limits imposed","PAC limit amount","PAC limits removed*amount","PAC limits imposed*amount",
                     "Individual-to-party limits removed","Individual-to-party limits imposed","Individual-to-party limit amount","Individual-to-party limits removed*amount","Individual-to-party limits imposed*amount"))

```

```{r stargazer DiD latex, results="asis", eval=T}
stargazer(CCIDID01, CCIDID02, CCIDID03, CRIDID01, CRIDID02, CRIDID03,
  title = "Do changes in limits lead to lower levels of corruption?",
  dep.var.labels = c("Corruption Convictions Index", "Corruption Reflections Index"),
  covariate.labels=c("Individual limits removed","Individual limits imposed","Individual limit amount","Individual limits removed*amount","Individual limits imposed*amount",
                     "PAC limits removed","PAC limits imposed","PAC limit amount","PAC limits removed*amount","PAC limits imposed*amount",
                     "Individual-to-party limits removed","Individual-to-party limits imposed","Individual-to-party limit amount","Individual-to-party limits removed*amount","Individual-to-party limits imposed*amount"))

```
