---
title: | 
  | Do campaign contribution limits limit corruption? 
  | Evidence from the 50 states
author: "Mark Hand"
date: "5/23/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, message=FALSE, warning=FALSE)
library(haven) # import .dta
library(tidyverse) # everything 
library(plm) # For linear panel regression
```

Since the 1970s, the U.S. Supreme Court has frustrated efforts at campaign finance reform by holding that nearly all limits on political spending violate the first amendment’s protection of free speech, with only one exception: to prevent “corruption of the appearance of corruption.” Using state-level data from 1990-2012 on contribution limits, corruption arrests, and media mentions of corruption, this paper employs a linear panel regression and a difference-in-differences analysis to test whether campaign contribution limits are associated with lower levels of corruption arrests or media mentions of corruption. These methods find no relationship between the presence or level of campaign finance laws and quid pro quo corruption. As current challenges to contribution limits wind their way through federal courts, the answer to this question will inform the Supreme Court’s decision to uphold or strike down remaining limits on political campaign contributions. 

\newpage 

##Introduction
In 1976, the Supreme Court ruled in Buckley v. Valeo that political campaign contributions are the equivalent of free speech, and therefore protected by the first amendment. At the same time, the Court laid out one mechanism and one justification for limiting those contributions. First, it argued that more money spent doesn’t amount of “more” speech, allowing for campaign contribution dollar amount limits. Donating one dollar or $5,000 to a political campaign amounts to a speech act, the Court held, and so it is permissible to impose limits on the amount of contributions as long as contributions are not prevented. Second, having laid out the mechanism by which money in politics might be limited, the court laid out the only justification for limiting contributions that it would accept moving forward: To prevent corruption or the appearance thereof. As Kang (2012) argues, the holdings in Buckley v. Valeo provided “the basic framework of contribution limits and disclosure requirements” for the following four decades. Since Buckley v. Valeo, Congress has passed only one campaign finance law, the Bipartisan Campaign Reform Act of 2002. Better know as McCain-Feingold, the bill took aim at unlimited “soft money” contributions to political parties and expanded the Federal Election Commission’s disclosure requirements to what it called “electioneering communications,” political ads not paid for by campaigns themselves. 

Apart from McCain-Feingold, for forty years all changes in the landscape of campaign finance have come from the courts, the majority being decided upon how to balance questions of free political speech versus corruption. Those rulings have often been driven by the question of corporations’ participation in the political process. In 1978, the Court extended free speech protections to corporations (First National Bank of Boston v. Bellotti). In 1986, it  and struck down efforts to restrict their expenditures to FEC-registered Political Action Committees (FEC v. Massachusetts Right to Life). Then in 1990, it upheld a ban on corporations using treasury funds to pay for issue advertisements, arguing for an extended definition of corruption, "the corrosive and distorting effects of immense aggregations of wealth that are accumulated with the help of the corporate form and that have little or no correlation to the public's support for the corporation's political ideas" (Austin v. Michigan State Chamber of Commerce, later overturned). 

The passage of the McCain-Feingold in 2002 inspired a wave of challenges to campaign contributions and expenditures, driven mostly by conservative and religious groups. In 2007, the Court examined the McCain-Feingold ban on airing issue advertisements close to election. Banning such ads, the Court argued, would have a chilling effect on free speech, and it struck down the ban (FEC v. Wisconsin Right to Life). Then, in 2010, the Court issued what has become one of its most well-known rulings: In Citizens United v. FEC (2010), it struck down limits on independent expenditures by outside groups, including corporations and unions. One critical aspect of Citizens United is the establishment of the principle that, according to Justice Anthony Kennedy, “independent expenditures do not lead to, or create the appearance of, quid pro quo corruption.” The Court’s emphasis on quid pro quo corruption as the only justification for contribution limits extended the following year, as it struck down an Arizona effort to level the political playing field with matching state campaign funds (Arizona Free Enterprise Club v. Bennett, 2011). 

Since 2011, the network of conservative legal groups behind Citizens United has continued to take aim at contribution limits as an unnecessary restriction of political speech, with a focus on individual contribution limits. The 1971 Federal Election Campaign Act placed a limit on the amount an individual could give to one campaign, in addition to two-year limits on the total amount an individual could give to political campaigns. In McCutcheon v. FEC (2014) James Bopp, one of the attorneys behind the Citizens United challenge, convinced the Court of the unconstitutionality of total individual limits. Another case, Holmes v. FEC (2017), targeted the distribution of individual campaign contribution across primary and general elections. In yet another, Lair v. Motl (2017), Bopp once again took aim at individual contribution limits, arguing that the state of Montana had not shown compelling evidence that campaign contribution limits decreased the risk of corruption. 

The Ninth Circuit Court of Appeals upheld Montana’s campaign contribution limits, but further challenges to contribution limits are likely. Bopp said that he planned to appeal the Ninth Circuit’s ruling. Even if that fails, Bopp and other conservative groups plan to carry on. “I handle a lot of cases,” he said after the 2014 McCutcheon ruling, “and I‘m not done yet.” Supreme Court Justice Clarence Thomas laid the groundwork for future challenges in his commentary on the McCutcheon decision by arguing that more dollars did, in fact, equate to more speech. Once established, that principle supports the argument that campaign contribution dollar amount limits are a potentially unconstitutional restriction on speech (Hurley & Debenedetti 2014, Zall 2017). 
